name: Backend CI with Docker

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t traqfoot-backend ./traqfoot-backend

      - name: Run Tests 
        run: |
          docker run traqfoot-backend yarn test